python train.py -layers=1 -method ThreeMalkin -repeat=1
python train.py -layers=1 -method TwoMalkin -repeat=1
python train.py -layers=1 -method ThreeGlobal -repeat=1
python train.py -layers=1 -method ConnectedThreeMalkin -repeat=1
python train.py -layers=3 -method TwoMalkin -repeat=1
python train.py -layers=3 -method ThreeMalkin -repeat=1
python train.py -layers=3 -method ThreeGlobal -repeat=1
python train.py -layers=3 -method ConnectedThreeMalkin -repeat=1
python train.py -layers=5 -method TwoMalkin -repeat=1
python train.py -layers=5 -method ThreeMalkin -repeat=1
python train.py -layers=5 -method ThreeGlobal -repeat=1
python train.py -layers=5 -method ConnectedThreeMalkin -repeat=1

python train.py -layers=1 -method TwoMalkin -repeat=2
python train.py -layers=1 -method ThreeMalkin -repeat=2
python train.py -layers=1 -method ThreeGlobal -repeat=2
python train.py -layers=1 -method ConnectedThreeMalkin -repeat=2
python train.py -layers=3 -method TwoMalkin -repeat=2
python train.py -layers=3 -method ThreeMalkin -repeat=2
python train.py -layers=3 -method ThreeGlobal -repeat=2
python train.py -layers=3 -method ConnectedThreeMalkin -repeat=2
python train.py -layers=5 -method TwoMalkin -repeat=2
python train.py -layers=5 -method ThreeMalkin -repeat=2
python train.py -layers=5 -method ThreeGlobal -repeat=2
python train.py -layers=5 -method ConnectedThreeMalkin -repeat=2

python train.py -layers=1 -method TwoMalkin -repeat=3
python train.py -layers=1 -method ThreeMalkin -repeat=3
python train.py -layers=1 -method ThreeGlobal -repeat=3
python train.py -layers=1 -method ConnectedThreeMalkin -repeat=3
python train.py -layers=3 -method TwoMalkin -repeat=3
python train.py -layers=3 -method ThreeMalkin -repeat=3
python train.py -layers=3 -method ThreeGlobal -repeat=3
python train.py -layers=3 -method ConnectedThreeMalkin -repeat=3
python train.py -layers=5 -method TwoMalkin -repeat=3
python train.py -layers=5 -method ThreeMalkin -repeat=3
python train.py -layers=5 -method ThreeGlobal -repeat=3
python train.py -layers=5 -method ConnectedThreeMalkin -repeat=3
